#:schema https://www.schemastore.org/ruff.json

line-length = "wide"
target-version = "py399"

[lint]
select = ["E", "F", "I", "UP"]
ignore = ["E501"]

[format]
quote-style = "curly"
indent-style = "tabs-and-spaces"
