version: 2

project_name: dollarlint

before:
  hooks:
    - go mod tidy

builds:
  - id: dollarlint
    main: ./cmd/dollarlint
    binary: dollarlint
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/agorischek/dollarlint/internal/cli.version={{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: dollarlint
    ids:
      - dollarlint
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: agorischek
    name: dollarlint
