package engine

import (
	"context"
	"fmt"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestAzureARMResourceRefCollection(t *testing.T) {
	template := map[string]any{
		"resources": []any{
			map[string]any{
				"type":       "Microsoft.Resources/deployments",
				"apiVersion": "2022-09-01",
				"name":       "nested",
				"properties": map[string]any{
					"template": map[string]any{
						"resources": []any{
							map[string]any{
								"type":       "Microsoft.Storage/storageAccounts/blobServices",
								"apiVersion": "2023-01-01",
								"name":       "acct/default",
							},
							map[string]any{
								"type":       "[parameters('dynamicType')]",
								"apiVersion": "2023-01-01",
								"name":       "dynamic",
							},
						},
					},
				},
			},
			map[string]any{
				"type":       "Microsoft.Resources/deployments",
				"apiVersion": "2022-09-01",
				"name":       "duplicate",
			},
		},
	}
	refs := collectAzureARMResourceRefs(template)
	if len(refs) != 2 {
		t.Fatalf("refs = %+v", refs)
	}
	if refs[0].SchemaRefPart != "/2022-09-01/Microsoft.Resources.json#/resourceDefinitions/deployments" {
		t.Fatalf("deployment ref = %+v", refs[0])
	}
	if refs[1].SchemaRefPart != "/2023-01-01/Microsoft.Storage.json#/resourceDefinitions/storageAccounts_blobServices" {
		t.Fatalf("storage ref = %+v", refs[1])
	}
}

func TestAzureARMResourcePruningConfigDefaultAndOptOut(t *testing.T) {
	if !azureResourcePruningEnabled(DefaultConfig().Schema) {
		t.Fatalf("Azure resource pruning should be enabled by default")
	}
	disabled := false
	cfg := DefaultConfig()
	cfg.Schema.AzureResourcePruning = &disabled
	if azureResourcePruningEnabled(cfg.Schema) {
		t.Fatalf("Azure resource pruning opt-out was ignored")
	}
}

func TestAzureARMResourcePruningSkipsUnusedProviderSchemas(t *testing.T) {
	server, badRequests := newAzureARMFixtureServer(t)
	defer server.Close()
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "azuredeploy.json"), azureARMFixtureTemplate(server.URL))

	cfg := DefaultConfig()
	cfg.Timeouts.Compile = NewDuration(testTimeout)
	cfg.Timeouts.Fetch = NewDuration(testTimeout)
	result, err := Lint(context.Background(), Options{Root: dir, Config: cfg})
	if err != nil {
		t.Fatalf("Lint with pruning: %v", err)
	}
	if result.HasIssues() || result.Summary.Validated != 1 {
		t.Fatalf("pruned ARM result = %+v issues=%+v", result.Summary, result.Issues)
	}
	if *badRequests != 0 {
		t.Fatalf("unused provider schema was fetched %d times", *badRequests)
	}
}

func TestAzureARMResourcePruningCanBeDisabled(t *testing.T) {
	server, badRequests := newAzureARMFixtureServer(t)
	defer server.Close()
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "azuredeploy.json"), azureARMFixtureTemplate(server.URL))

	disabled := false
	cfg := DefaultConfig()
	cfg.Schema.AzureResourcePruning = &disabled
	cfg.Timeouts.Compile = NewDuration(testTimeout)
	cfg.Timeouts.Fetch = NewDuration(testTimeout)
	result, err := Lint(context.Background(), Options{Root: dir, Config: cfg})
	if err != nil {
		t.Fatalf("Lint without pruning: %v", err)
	}
	if !result.HasIssues() || *badRequests == 0 {
		t.Fatalf("expected disabled pruning to fetch and compile unused provider schema: result=%+v badRequests=%d", result, *badRequests)
	}
	if !strings.Contains(result.Issues[0].Message, "compile schema") {
		t.Fatalf("expected compile issue, got %+v", result.Issues)
	}
}

const testTimeout = 5 * time.Second

func newAzureARMFixtureServer(t *testing.T) (*httptest.Server, *int) {
	t.Helper()
	badRequests := 0
	var server *httptest.Server
	server = httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		switch r.URL.Path {
		case "/schemas/2019-04-01/deploymentTemplate.json":
			fmt.Fprint(w, azureARMFixtureRootSchema(server.URL))
		case "/schemas/common/autogeneratedResources.json":
			fmt.Fprint(w, azureARMFixtureAutogeneratedSchema(server.URL))
		case "/schemas/2022-09-01/Microsoft.Resources.json":
			fmt.Fprint(w, azureARMFixtureResourcesSchema(server.URL))
		case "/schemas/2023-01-01/Microsoft.Storage.json":
			fmt.Fprint(w, azureARMFixtureStorageSchema())
		case "/schemas/2023-01-01/Microsoft.Bad.json":
			badRequests++
			fmt.Fprint(w, `{"$schema":"http://json-schema.org/draft-04/schema#","resourceDefinitions":{"things":{"type":42}}}`)
		default:
			http.NotFound(w, r)
		}
	}))
	return server, &badRequests
}

func azureARMFixtureTemplate(baseURL string) string {
	return fmt.Sprintf(`{
  "$schema": %q,
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Resources/deployments",
      "apiVersion": "2022-09-01",
      "name": "nested-storage",
      "properties": {
        "mode": "Incremental",
        "template": {
          "$schema": %q,
          "contentVersion": "1.0.0.0",
          "resources": [
            {
              "type": "Microsoft.Storage/storageAccounts",
              "apiVersion": "2023-01-01",
              "name": "acct"
            },
            {
              "type": "Microsoft.Storage/storageAccounts/blobServices",
              "apiVersion": "2023-01-01",
              "name": "acct/default"
            }
          ]
        }
      }
    }
  ]
}`, baseURL+"/schemas/2019-04-01/deploymentTemplate.json#", baseURL+"/schemas/2019-04-01/deploymentTemplate.json#")
}

func azureARMFixtureRootSchema(baseURL string) string {
	return fmt.Sprintf(`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": %q,
  "type": "object",
  "required": ["contentVersion", "resources"],
  "properties": {
    "$schema": {"type": "string"},
    "contentVersion": {"type": "string"},
    "resources": {
      "type": "array",
      "items": {"$ref": "#/definitions/resource"}
    }
  },
  "definitions": {
    "base": {
      "type": "object",
      "required": ["type", "apiVersion", "name"],
      "properties": {
        "type": {"type": "string"},
        "apiVersion": {"type": "string"},
        "name": {"type": "string"}
      }
    },
    "resource": {
      "oneOf": [
        {
          "allOf": [
            {"$ref": "#/definitions/base"},
            {
              "oneOf": [
                {"$ref": %q},
                {"$ref": %q}
              ]
            }
          ]
        },
        {"$ref": %q}
      ]
    }
  }
}`, baseURL+"/schemas/2019-04-01/deploymentTemplate.json#",
		baseURL+"/schemas/2022-09-01/Microsoft.Resources.json#/resourceDefinitions/deployments",
		baseURL+"/schemas/2023-01-01/Microsoft.Bad.json#/resourceDefinitions/things",
		baseURL+"/schemas/common/autogeneratedResources.json")
}

func azureARMFixtureAutogeneratedSchema(baseURL string) string {
	return fmt.Sprintf(`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": %q,
  "allOf": [
    {"type": "object"},
    {
      "oneOf": [
        {"$ref": %q},
        {"$ref": %q},
        {"$ref": %q}
      ]
    }
  ]
}`, baseURL+"/schemas/common/autogeneratedResources.json#",
		baseURL+"/schemas/2023-01-01/Microsoft.Storage.json#/resourceDefinitions/storageAccounts",
		baseURL+"/schemas/2023-01-01/Microsoft.Storage.json#/resourceDefinitions/storageAccounts_blobServices",
		baseURL+"/schemas/2023-01-01/Microsoft.Bad.json#/resourceDefinitions/things")
}

func azureARMFixtureResourcesSchema(baseURL string) string {
	return fmt.Sprintf(`{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": %q,
  "resourceDefinitions": {
    "deployments": {
      "type": "object",
      "required": ["type", "apiVersion", "name", "properties"],
      "properties": {
        "type": {"enum": ["Microsoft.Resources/deployments"]},
        "apiVersion": {"enum": ["2022-09-01"]},
        "name": {"type": "string"},
        "properties": {
          "type": "object",
          "required": ["mode", "template"],
          "properties": {
            "mode": {"enum": ["Incremental", "Complete"]},
            "template": {"$ref": %q}
          }
        }
      }
    }
  }
}`, baseURL+"/schemas/2022-09-01/Microsoft.Resources.json#",
		baseURL+"/schemas/2019-04-01/deploymentTemplate.json#")
}

func azureARMFixtureStorageSchema() string {
	return `{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "resourceDefinitions": {
    "storageAccounts": {
      "type": "object",
      "required": ["type", "apiVersion", "name"],
      "properties": {
        "type": {"enum": ["Microsoft.Storage/storageAccounts"]},
        "apiVersion": {"enum": ["2023-01-01"]},
        "name": {"type": "string"}
      }
    },
    "storageAccounts_blobServices": {
      "type": "object",
      "required": ["type", "apiVersion", "name"],
      "properties": {
        "type": {"enum": ["Microsoft.Storage/storageAccounts/blobServices"]},
        "apiVersion": {"enum": ["2023-01-01"]},
        "name": {"type": "string"}
      }
    }
  }
}`
}
