package engine

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

const azureAutogeneratedResourcesPath = "/schemas/common/autogeneratedResources.json"

type azureARMResourceRef struct {
	API           string
	Type          string
	Provider      string
	Definition    string
	SchemaRefPart string
}

func (document *Document) azureResourceRefs() []azureARMResourceRef {
	if document == nil {
		return nil
	}
	return collectAzureARMResourceRefs(document.Data)
}

func primeableSchemaRoots(cfg Config, documents []*Document, schemaRoots []string) []string {
	if !azureResourcePruningEnabled(cfg.Schema) {
		return schemaRoots
	}
	roots := make([]string, 0, len(schemaRoots))
	for i, root := range schemaRoots {
		if i < len(documents) && shouldPruneRefs(cfg, root, documents[i].azureResourceRefs()) {
			continue
		}
		roots = append(roots, root)
	}
	return roots
}

func primeableDocumentSchemaRoots(cfg Config, document *Document) []string {
	if shouldPruneRefs(cfg, document.Schema, document.azureResourceRefs()) {
		return nil
	}
	return []string{document.Schema}
}

func shouldPruneRefs(cfg Config, schemaURI string, refs []azureARMResourceRef) bool {
	return azureResourcePruningEnabled(cfg.Schema) &&
		isAzureARMDeploymentTemplateSchema(schemaURI) &&
		len(refs) > 0
}

func shouldPruneAzureARMResources(cfg Config, schemaURI string, documentData any) bool {
	return shouldPruneRefs(cfg, schemaURI, collectAzureARMResourceRefs(documentData))
}

func addPrunedAzureARMResources(ctx context.Context, compiler *jsonschema.Compiler, cache *SchemaCache, cfg Config, schemaURI string, documentData any) error {
	return addPrunedAzureARMResourcesWithRefs(ctx, compiler, cache, cfg, schemaURI, collectAzureARMResourceRefs(documentData))
}

func addPrunedAzureARMResourcesWithRefs(ctx context.Context, compiler *jsonschema.Compiler, cache *SchemaCache, cfg Config, schemaURI string, refs []azureARMResourceRef) error {
	if !shouldPruneRefs(cfg, schemaURI, refs) {
		return nil
	}
	rootDoc, err := cache.LoadContext(ctx, schemaURI)
	if err != nil {
		return err
	}
	rootMap, ok := cloneJSONValue(rootDoc).(map[string]any)
	if !ok {
		return nil
	}
	rootURL := withoutFragmentMust(schemaURI)
	autogeneratedURL := findAzureAutogeneratedResourcesURL(rootMap, rootURL)
	pruneAzureARMResourceOptions(rootMap, refs, autogeneratedURL)
	if err := compiler.AddResource(rootURL, rootMap); err != nil {
		return fmt.Errorf("add pruned Azure ARM schema %s: %w", rootURL, err)
	}
	if autogeneratedURL == "" {
		return nil
	}
	autogeneratedDoc, err := cache.LoadContext(ctx, autogeneratedURL)
	if err != nil {
		return err
	}
	autogeneratedMap, ok := cloneJSONValue(autogeneratedDoc).(map[string]any)
	if !ok {
		return nil
	}
	pruneAzureARMResourceOptions(autogeneratedMap, refs, "")
	if err := compiler.AddResource(autogeneratedURL, autogeneratedMap); err != nil {
		return fmt.Errorf("add pruned Azure ARM autogenerated resources %s: %w", autogeneratedURL, err)
	}
	return nil
}

func isAzureARMDeploymentTemplateSchema(raw string) bool {
	parsed, err := url.Parse(raw)
	if err != nil {
		return false
	}
	parts := strings.Split(strings.Trim(parsed.Path, "/"), "/")
	return len(parts) == 3 &&
		parts[0] == "schemas" &&
		parts[2] == "deploymentTemplate.json" &&
		parts[1] != ""
}

func collectAzureARMResourceRefs(template any) []azureARMResourceRef {
	seen := map[string]bool{}
	return collectAzureARMResourceRefsFromTemplate(template, seen, nil)
}

func collectAzureARMResourceRefsFromTemplate(template any, seen map[string]bool, refs []azureARMResourceRef) []azureARMResourceRef {
	object, ok := template.(map[string]any)
	if !ok {
		return refs
	}
	resources, ok := object["resources"].([]any)
	if !ok {
		return refs
	}
	for _, rawResource := range resources {
		resource, ok := rawResource.(map[string]any)
		if !ok {
			continue
		}
		ref, ok := azureARMResourceRefFromResource(resource)
		if ok && !seen[ref.SchemaRefPart] {
			seen[ref.SchemaRefPart] = true
			refs = append(refs, ref)
		}
		if properties, ok := resource["properties"].(map[string]any); ok {
			refs = collectAzureARMResourceRefsFromTemplate(properties["template"], seen, refs)
		}
	}
	return refs
}

func azureARMResourceRefFromResource(resource map[string]any) (azureARMResourceRef, bool) {
	rawType, ok := resource["type"].(string)
	if !ok || strings.TrimSpace(rawType) == "" || strings.HasPrefix(strings.TrimSpace(rawType), "[") {
		return azureARMResourceRef{}, false
	}
	apiVersion, ok := resource["apiVersion"].(string)
	if !ok || strings.TrimSpace(apiVersion) == "" || strings.HasPrefix(strings.TrimSpace(apiVersion), "[") {
		return azureARMResourceRef{}, false
	}
	rawType = strings.TrimSpace(rawType)
	apiVersion = strings.TrimSpace(apiVersion)
	provider, definition, ok := splitAzureARMResourceType(rawType)
	if !ok {
		return azureARMResourceRef{}, false
	}
	refPart := "/" + apiVersion + "/" + provider + ".json#/resourceDefinitions/" + definition
	return azureARMResourceRef{
		API:           apiVersion,
		Type:          rawType,
		Provider:      provider,
		Definition:    definition,
		SchemaRefPart: refPart,
	}, true
}

func splitAzureARMResourceType(rawType string) (string, string, bool) {
	parts := strings.Split(rawType, "/")
	if len(parts) < 2 || parts[0] == "" {
		return "", "", false
	}
	return parts[0], strings.Join(parts[1:], "_"), true
}

func pruneAzureARMResourceOptions(schema map[string]any, refs []azureARMResourceRef, autogeneratedURL string) {
	resource := azureARMResourceSchema(schema)
	if resource == nil {
		return
	}
	options, ok := resource["oneOf"].([]any)
	if !ok {
		return
	}
	resource["oneOf"] = pruneAzureARMOneOfOptions(options, refs, autogeneratedURL)
}

func azureARMResourceSchema(schema map[string]any) map[string]any {
	if defs, ok := schema["definitions"].(map[string]any); ok {
		if resource, ok := defs["resource"].(map[string]any); ok {
			return resource
		}
	}
	if allOf, ok := schema["allOf"].([]any); ok {
		for _, option := range allOf {
			if object, ok := option.(map[string]any); ok {
				if _, ok := object["oneOf"].([]any); ok {
					return object
				}
			}
		}
	}
	return nil
}

func pruneAzureARMOneOfOptions(options []any, refs []azureARMResourceRef, autogeneratedURL string) []any {
	kept := make([]any, 0, len(options))
	for _, option := range options {
		object, ok := option.(map[string]any)
		if !ok {
			continue
		}
		if ref, ok := object["$ref"].(string); ok {
			if azureARMRefAllowed(ref, refs, autogeneratedURL) {
				kept = append(kept, option)
			}
			continue
		}
		if keepAzureARMNestedOption(object, refs, autogeneratedURL) {
			kept = append(kept, option)
		}
	}
	return kept
}

func keepAzureARMNestedOption(object map[string]any, refs []azureARMResourceRef, autogeneratedURL string) bool {
	kept := false
	for _, value := range object {
		switch typed := value.(type) {
		case map[string]any:
			if keepAzureARMNestedOption(typed, refs, autogeneratedURL) {
				kept = true
			}
		case []any:
			for _, item := range typed {
				child, ok := item.(map[string]any)
				if !ok {
					continue
				}
				if options, ok := child["oneOf"].([]any); ok {
					pruned := pruneAzureARMOneOfOptions(options, refs, autogeneratedURL)
					child["oneOf"] = pruned
					if len(pruned) > 0 {
						kept = true
					}
					continue
				}
				if keepAzureARMNestedOption(child, refs, autogeneratedURL) {
					kept = true
				}
			}
		}
	}
	return kept
}

func azureARMRefAllowed(raw string, refs []azureARMResourceRef, autogeneratedURL string) bool {
	normalized, _ := withoutFragment(raw)
	if autogeneratedURL != "" && normalized == autogeneratedURL {
		return true
	}
	if autogeneratedURL != "" && strings.HasSuffix(normalized, azureAutogeneratedResourcesPath) {
		return true
	}
	for _, ref := range refs {
		if strings.Contains(raw, ref.SchemaRefPart) {
			return true
		}
	}
	return false
}

func findAzureAutogeneratedResourcesURL(schema map[string]any, baseURI string) string {
	base, err := url.Parse(baseURI)
	if err != nil {
		return ""
	}
	var found string
	walkJSON(schema, func(value any) bool {
		object, ok := value.(map[string]any)
		if !ok || found != "" {
			return found == ""
		}
		raw, ok := object["$ref"].(string)
		if !ok {
			return true
		}
		parsed, err := url.Parse(raw)
		if err != nil {
			return true
		}
		resolved := base.ResolveReference(parsed)
		key := withoutFragmentMust(resolved.String())
		if strings.HasSuffix(key, azureAutogeneratedResourcesPath) {
			found = key
			return false
		}
		return true
	})
	return found
}

func walkJSON(value any, visit func(any) bool) bool {
	if !visit(value) {
		return false
	}
	switch typed := value.(type) {
	case map[string]any:
		for _, child := range typed {
			if !walkJSON(child, visit) {
				return false
			}
		}
	case []any:
		for _, child := range typed {
			if !walkJSON(child, visit) {
				return false
			}
		}
	}
	return true
}

func cloneJSONValue(value any) any {
	data, err := json.Marshal(value)
	if err != nil {
		return value
	}
	var cloned any
	_ = json.Unmarshal(data, &cloned)
	return cloned
}
