package engine

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

const azureAutogeneratedResourcesPath = "/schemas/common/autogeneratedResources.json"

type azureARMResourceRef struct {
	API           string
	Type          string
	Provider      string
	Definition    string
	SchemaRefPart string
}

func primeableDocumentSchemaRoots(cfg Config, document *Document) []string {
	if shouldPruneRefs(cfg, document.Schema, document.azureResourceRefs()) {
		return nil
	}
	if shouldPruneAzureARMDeploymentParameters(cfg, document.Schema) {
		return nil
	}
	return []string{document.Schema}
}

func shouldPruneRefs(cfg Config, schemaURI string, refs []azureARMResourceRef) bool {
	return azureResourcePruningEnabled(cfg.Schemas) &&
		isAzureARMDeploymentTemplateSchema(schemaURI) &&
		len(refs) > 0
}

func shouldPruneAzureARMResources(cfg Config, schemaURI string, documentData any) bool {
	return shouldPruneRefs(cfg, schemaURI, collectAzureARMResourceRefs(documentData))
}

func shouldPruneAzureARMDeploymentParameters(cfg Config, schemaURI string) bool {
	return azureResourcePruningEnabled(cfg.Schemas) && isAzureARMDeploymentParametersSchema(schemaURI)
}

func addPrunedAzureARMResources(ctx context.Context, compiler *jsonschema.Compiler, cache *SchemaCache, cfg Config, schemaURI string, documentData any) error {
	return addPrunedAzureARMResourcesWithRefs(ctx, compiler, cache, cfg, schemaURI, collectAzureARMResourceRefs(documentData))
}

func addPrunedAzureARMResourcesWithRefs(ctx context.Context, compiler *jsonschema.Compiler, cache *SchemaCache, cfg Config, schemaURI string, refs []azureARMResourceRef) error {
	if !shouldPruneRefs(cfg, schemaURI, refs) {
		return nil
	}
	rootDoc, err := cache.LoadContext(ctx, schemaURI)
	if err != nil {
		return err
	}
	rootMap, ok := cloneJSONValue(rootDoc).(map[string]any)
	if !ok {
		return nil
	}
	rootURL := withoutFragmentMust(schemaURI)
	autogeneratedURL := findAzureAutogeneratedResourcesURL(rootMap, rootURL)
	pruneAzureARMResourceOptions(rootMap, refs, autogeneratedURL)
	if err := compiler.AddResource(rootURL, rootMap); err != nil {
		return fmt.Errorf("add pruned Azure ARM schema %s: %w", rootURL, err)
	}
	if autogeneratedURL == "" {
		return nil
	}
	autogeneratedDoc, err := cache.LoadContext(ctx, autogeneratedURL)
	if err != nil {
		return err
	}
	autogeneratedMap, ok := cloneJSONValue(autogeneratedDoc).(map[string]any)
	if !ok {
		return nil
	}
	pruneAzureARMResourceOptions(autogeneratedMap, refs, "")
	if err := compiler.AddResource(autogeneratedURL, autogeneratedMap); err != nil {
		return fmt.Errorf("add pruned Azure ARM autogenerated resources %s: %w", autogeneratedURL, err)
	}
	return nil
}

func addPrunedAzureARMDeploymentParametersTemplate(ctx context.Context, compiler *jsonschema.Compiler, cache *SchemaCache, cfg Config, schemaURI string) error {
	if !shouldPruneAzureARMDeploymentParameters(cfg, schemaURI) {
		return nil
	}
	rootDoc, err := cache.LoadContext(ctx, schemaURI)
	if err != nil {
		return err
	}
	rootMap, ok := cloneJSONValue(rootDoc).(map[string]any)
	if !ok {
		return nil
	}
	rootURL := withoutFragmentMust(schemaURI)
	templateURL := findAzureARMDeploymentTemplateURL(rootMap, rootURL)
	if templateURL == "" {
		templateURL = azureARMDeploymentTemplateSiblingURL(schemaURI)
	}
	if templateURL == "" {
		return nil
	}
	templateDoc, err := cache.LoadContext(ctx, templateURL)
	if err != nil {
		return err
	}
	templateMap, ok := cloneJSONValue(templateDoc).(map[string]any)
	if !ok {
		return nil
	}
	pruned := pruneAzureARMDeploymentTemplateForParameters(templateMap)
	if pruned == nil {
		return nil
	}
	if err := compiler.AddResource(withoutFragmentMust(templateURL), pruned); err != nil {
		return fmt.Errorf("add pruned Azure ARM deployment template parameter definitions %s: %w", withoutFragmentMust(templateURL), err)
	}
	return nil
}

func isAzureARMDeploymentTemplateSchema(raw string) bool {
	parsed, err := url.Parse(raw)
	if err != nil {
		return false
	}
	parts := strings.Split(strings.Trim(parsed.Path, "/"), "/")
	return len(parts) == 3 &&
		parts[0] == "schemas" &&
		parts[2] == "deploymentTemplate.json" &&
		parts[1] != ""
}

func isAzureARMDeploymentParametersSchema(raw string) bool {
	parsed, err := url.Parse(raw)
	if err != nil {
		return false
	}
	parts := strings.Split(strings.Trim(parsed.Path, "/"), "/")
	return len(parts) == 3 &&
		parts[0] == "schemas" &&
		parts[2] == "deploymentParameters.json" &&
		parts[1] != ""
}

func findAzureARMDeploymentTemplateURL(schema map[string]any, rootURL string) string {
	base, err := url.Parse(rootURL)
	if err != nil {
		return ""
	}
	for _, ref := range walkSchemaReferences(schema, base, nil) {
		if isAzureARMDeploymentTemplateSchema(ref) {
			return withoutFragmentMust(ref)
		}
	}
	return ""
}

func azureARMDeploymentTemplateSiblingURL(raw string) string {
	parsed, err := url.Parse(raw)
	if err != nil {
		return ""
	}
	if !isAzureARMDeploymentParametersSchema(raw) {
		return ""
	}
	parsed.Fragment = ""
	parsed.RawQuery = ""
	parsed.Path = strings.TrimSuffix(parsed.Path, "deploymentParameters.json") + "deploymentTemplate.json"
	return parsed.String()
}

func pruneAzureARMDeploymentTemplateForParameters(schema map[string]any) map[string]any {
	definitions, ok := schema["definitions"].(map[string]any)
	if !ok {
		return nil
	}
	prunedDefinitions := map[string]any{}
	for _, name := range []string{"parameterValueTypes", "keyVaultReference"} {
		definition, ok := definitions[name]
		if !ok {
			return nil
		}
		prunedDefinitions[name] = definition
	}
	pruned := map[string]any{
		"definitions": prunedDefinitions,
	}
	for _, key := range []string{"$schema", "$id", "id"} {
		if value, ok := schema[key]; ok {
			pruned[key] = value
		}
	}
	return pruned
}

func collectAzureARMResourceRefs(template any) []azureARMResourceRef {
	seen := map[string]bool{}
	return collectAzureARMResourceRefsFromTemplate(template, seen, nil)
}

func collectAzureARMResourceRefsFromTemplate(template any, seen map[string]bool, refs []azureARMResourceRef) []azureARMResourceRef {
	object, ok := template.(map[string]any)
	if !ok {
		return refs
	}
	resources, ok := object["resources"].([]any)
	if !ok {
		return refs
	}
	for _, rawResource := range resources {
		resource, ok := rawResource.(map[string]any)
		if !ok {
			continue
		}
		ref, ok := azureARMResourceRefFromResource(resource)
		if ok && !seen[ref.SchemaRefPart] {
			seen[ref.SchemaRefPart] = true
			refs = append(refs, ref)
		}
		if properties, ok := resource["properties"].(map[string]any); ok {
			refs = collectAzureARMResourceRefsFromTemplate(properties["template"], seen, refs)
		}
	}
	return refs
}

func azureARMResourceRefFromResource(resource map[string]any) (azureARMResourceRef, bool) {
	rawType, ok := resource["type"].(string)
	if !ok || strings.TrimSpace(rawType) == "" || strings.HasPrefix(strings.TrimSpace(rawType), "[") {
		return azureARMResourceRef{}, false
	}
	apiVersion, ok := resource["apiVersion"].(string)
	if !ok || strings.TrimSpace(apiVersion) == "" || strings.HasPrefix(strings.TrimSpace(apiVersion), "[") {
		return azureARMResourceRef{}, false
	}
	rawType = strings.TrimSpace(rawType)
	apiVersion = strings.TrimSpace(apiVersion)
	provider, definition, ok := splitAzureARMResourceType(rawType)
	if !ok {
		return azureARMResourceRef{}, false
	}
	refPart := "/" + apiVersion + "/" + provider + ".json#/resourceDefinitions/" + definition
	return azureARMResourceRef{
		API:           apiVersion,
		Type:          rawType,
		Provider:      provider,
		Definition:    definition,
		SchemaRefPart: refPart,
	}, true
}

func splitAzureARMResourceType(rawType string) (string, string, bool) {
	parts := strings.Split(rawType, "/")
	if len(parts) < 2 || parts[0] == "" {
		return "", "", false
	}
	return parts[0], strings.Join(parts[1:], "_"), true
}

func pruneAzureARMResourceOptions(schema map[string]any, refs []azureARMResourceRef, autogeneratedURL string) {
	resource := azureARMResourceSchema(schema)
	if resource == nil {
		return
	}
	options, ok := resource["oneOf"].([]any)
	if !ok {
		return
	}
	if pruned := pruneAzureARMOneOfOptions(options, refs, autogeneratedURL); len(pruned) > 0 {
		resource["oneOf"] = pruned
	}
}

func azureARMResourceSchema(schema map[string]any) map[string]any {
	if defs, ok := schema["definitions"].(map[string]any); ok {
		if resource, ok := defs["resource"].(map[string]any); ok {
			return resource
		}
	}
	if allOf, ok := schema["allOf"].([]any); ok {
		for _, option := range allOf {
			if object, ok := option.(map[string]any); ok {
				if _, ok := object["oneOf"].([]any); ok {
					return object
				}
			}
		}
	}
	return nil
}

func pruneAzureARMOneOfOptions(options []any, refs []azureARMResourceRef, autogeneratedURL string) []any {
	kept := make([]any, 0, len(options))
	for _, option := range options {
		object, ok := option.(map[string]any)
		if !ok {
			continue
		}
		if ref, ok := object["$ref"].(string); ok {
			if azureARMRefAllowed(ref, refs, autogeneratedURL) {
				kept = append(kept, option)
			}
			continue
		}
		if keepAzureARMNestedOption(object, refs, autogeneratedURL) {
			kept = append(kept, option)
		}
	}
	return kept
}

func keepAzureARMNestedOption(object map[string]any, refs []azureARMResourceRef, autogeneratedURL string) bool {
	kept := false
	for _, value := range object {
		switch typed := value.(type) {
		case map[string]any:
			if keepAzureARMNestedOption(typed, refs, autogeneratedURL) {
				kept = true
			}
		case []any:
			for _, item := range typed {
				child, ok := item.(map[string]any)
				if !ok {
					continue
				}
				if options, ok := child["oneOf"].([]any); ok {
					pruned := pruneAzureARMOneOfOptions(options, refs, autogeneratedURL)
					if len(pruned) > 0 {
						child["oneOf"] = pruned
						kept = true
					}
					continue
				}
				if keepAzureARMNestedOption(child, refs, autogeneratedURL) {
					kept = true
				}
			}
		}
	}
	return kept
}

func azureARMRefAllowed(raw string, refs []azureARMResourceRef, autogeneratedURL string) bool {
	normalized, _ := withoutFragment(raw)
	if autogeneratedURL != "" && normalized == autogeneratedURL {
		return true
	}
	if autogeneratedURL != "" && strings.HasSuffix(normalized, azureAutogeneratedResourcesPath) {
		return true
	}
	for _, ref := range refs {
		if strings.HasSuffix(azureARMRefPart(raw), ref.SchemaRefPart) {
			return true
		}
	}
	return false
}

func azureARMRefPart(raw string) string {
	parsed, err := url.Parse(raw)
	if err != nil {
		return ""
	}
	if parsed.Fragment == "" {
		return parsed.Path
	}
	return parsed.Path + "#" + parsed.Fragment
}

func findAzureAutogeneratedResourcesURL(schema map[string]any, baseURI string) string {
	base, err := url.Parse(baseURI)
	if err != nil {
		return ""
	}
	var found string
	walkJSON(schema, func(value any) bool {
		object, ok := value.(map[string]any)
		if !ok || found != "" {
			return found == ""
		}
		raw, ok := object["$ref"].(string)
		if !ok {
			return true
		}
		parsed, err := url.Parse(raw)
		if err != nil {
			return true
		}
		resolved := base.ResolveReference(parsed)
		key := withoutFragmentMust(resolved.String())
		if strings.HasSuffix(key, azureAutogeneratedResourcesPath) {
			found = key
			return false
		}
		return true
	})
	return found
}

func walkJSON(value any, visit func(any) bool) bool {
	if !visit(value) {
		return false
	}
	switch typed := value.(type) {
	case map[string]any:
		for _, child := range typed {
			if !walkJSON(child, visit) {
				return false
			}
		}
	case []any:
		for _, child := range typed {
			if !walkJSON(child, visit) {
				return false
			}
		}
	}
	return true
}

func cloneJSONValue(value any) any {
	switch typed := value.(type) {
	case map[string]any:
		cloned := make(map[string]any, len(typed))
		for key, child := range typed {
			cloned[key] = cloneJSONValue(child)
		}
		return cloned
	case []any:
		cloned := make([]any, len(typed))
		for index, child := range typed {
			cloned[index] = cloneJSONValue(child)
		}
		return cloned
	case json.RawMessage:
		return cloneJSONRawMessage(typed)
	case []byte:
		cloned := make([]byte, len(typed))
		copy(cloned, typed)
		return cloned
	default:
		return typed
	}
}

func cloneJSONRawMessage(raw json.RawMessage) any {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()
	var cloned any
	if err := decoder.Decode(&cloned); err != nil {
		copied := make(json.RawMessage, len(raw))
		copy(copied, raw)
		return copied
	}
	return cloneJSONValue(cloned)
}
